/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const clear_state: () => void;
export const create_group: (a: number, b: number) => [number, number];
export const create_invite: (a: number, b: number, c: number, d: number) => [number, number, number];
export const decrypt_message: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const encrypt_message: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const generate_key_packages: (a: number) => [number, number, number];
export const has_group_state: (a: number, b: number) => number;
export const init_mls: (a: number, b: number) => [number, number];
export const process_commit: (a: number, b: number, c: number, d: number) => [number, number];
export const process_welcome: (a: number, b: number) => [number, number, number, number];
export const save_state_to_storage: (a: number, b: number) => [number, number];
export const __wbg_wasmbindgentestcontext_free: (a: number, b: number) => void;
export const __wbgtest_console_debug: (a: any) => void;
export const __wbgtest_console_error: (a: any) => void;
export const __wbgtest_console_info: (a: any) => void;
export const __wbgtest_console_log: (a: any) => void;
export const __wbgtest_console_warn: (a: any) => void;
export const wasmbindgentestcontext_filtered_count: (a: number, b: number) => void;
export const wasmbindgentestcontext_include_ignored: (a: number, b: number) => void;
export const wasmbindgentestcontext_new: (a: number) => number;
export const wasmbindgentestcontext_run: (a: number, b: number, c: number) => any;
export const __wbgbench_dump: () => [number, number];
export const __wbgbench_import: (a: number, b: number) => void;
export const __wbgtest_cov_dump: () => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h4319133022181043: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h995dd7520031f68d: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h255a89ae68d7021b: (a: number, b: number, c: any, d: number, e: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1c2f29fb06bfab95: (a: number, b: number, c: any, d: any) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
